package main

// This file is auto-generated by `tplize`.
// `tplize` make contents of non-Go files to Go variable,
// so that your binary can use them.
// See https://github.com/otiai10/tplize for more information.

// Tpl is template pool.
var Tpl = map[string]string{
	// index.html
	"index.html": `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" />
</head>
<body>
  <div class="container">
    <h1>C<span style="color:#FFE900">o</span>l<span style="color:#28AFB0">o</span>r Ch<span style="color:#E53D00">a</span>t</h1>
  </div>
  <div class="container">
    <div class="row">
      <div class="eight columns"><input name="message" class="u-full-width" type="text" placeholder="message here" style="font-size:1em;" required/></div>
      <div class="four  columns"><input class="button-primary u-full-width" type="submit" value="send" /></div>
    </div>
  </div>
  <div class="container">
    <ul id="timeline"></ul>
  </div>
  <script type="text/javascript" src="/public/main.js"></script>
</body>
</html>
`,
}
